### ISSUE TITLE
Error in Visual DES algorithm

### ISSUE THREAD

**Issue by Snd18** [jcryptool/core#103]
Hello,

I have found a little mistake in the algorithm study part within the Inner States of the DES . The manual key provides by the user is never assigned to the algorithm. The program is always working with the default user key:
```java
    int[] key_user = { 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 
    1, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1 };
```

The problem is in the DESController.java. It has the following code:
```java
    if (checkAlgInput() != 0) {
          return 1;
    }
```
but you never call the method public void convert_Hex_To_Binary(String hex) in the DESModel class. In this method is where the key provides by the user is assigned to the program:
```java
    public void convert_Hex_To_Binary(String hex)
    {
        String binary_string = hexToBinary(hex, true);
        int[] data = new int[64];
        for (int k = 0; k < data.length; k++) {
        data[k] = Character.getNumericValue(binary_string.charAt(k));
    }
        this.key_user = data;
    }
```

Therefore, the algorithm is never using the key provides by the user. In my opinion you should add an else in the DESController.java in that way:
```java
    if (checkAlgInput() != 0) {
          return 1;
    } else {
          this.DESMod.convert_Hex_To_Binary(this.Alg_In_manualKey );
    }
```
Please, check if it is correct and, in that case, fix it in the new version.

Regards,
Sandra.

**Comment by dschadow** [comment]
Thank your for your analysis. Since the original developer is not active any more I have integrated your recommendation into our code base (good job pointing that out, this code is neither easy to read nor easy to understand!). The next weekly build on June 20th will contain these changes.
