### ISSUE TITLE
NSIS installer (setup.exe) requires admin rights

### ISSUE THREAD

**Issue by rofrol** [jcryptool/core#104]
Installing KDiff3-64bit-Setup_0.9.98-2.exe on Windows 7 Enterprise. Still asks for admin password

same as closed #20

**Comment by dschadow** [comment]
Confirmed. Since Eclipse NSIS is not active (any more) we will have to find another solution to provide native installers. Maybe we can use [Eclipse Oomph](https://wiki.eclipse.org/Eclipse_Installer) in the future.

**Comment by dschadow** [comment]
Closing this ticket since we need a new installer and can't fix NSIS any more.
