### ISSUE TITLE
Create installers for JCrypTool

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#111]
Since NSIS is not supported/ developed any more we need a way to create installers. Maybe [Eclipse Oomph](https://projects.eclipse.org/projects/tools.oomph) is a possibility for OS X and Windows.

**Comment by be4** [comment]
As I could see this is the default installer for Eclipse projects. So it should be used.
Good collection of information is here. http://wiki.eclipse.org/Eclipse_Oomph_Installer

**Comment by dschadow** [comment]
Since installation is possible with a simple extract this task will be closed.
