### ISSUE TITLE
Might want to add instructions about opening unsigned .apps on OS X

### ISSUE THREAD

**Issue by KingMob** [jcryptool/core#116]
By default, the current stable jCryptTool .app won't open in Sierra because it's not signed. That can be bypassed by holding Control, right-clicking, and choosing "Open" (https://support.apple.com/kb/PH25088?locale=en_US).

If you don't want to pay Apple to sign it, you may want to update the instructions at https://www.cryptool.org/en/jcryptool-en/88-installation-en

**Comment by dschadow** [comment]
Thanks for the hint, we will do that.

**Comment by dschadow** [comment]
Updated German and English installation instructions.
