### ISSUE TITLE
Thoroughly test configuration stability when migrating to a new JCT version

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#118]
I suspect, that problems like #117 may be caused by earlier JCT versions writing (JCT workspace state-) persistence files that are not fully compatible with prior JCrypTool versions, causing erroneus behavior. Although it is by no means a big problem, it could be systematic.

- first step could be to somehow try to reproduce #117 by this angle - switch JCT versions, cleanup or not of ~/Documents/.jcryptool, ...
- investigate which plugins write configuration into .jcryptool how - in a unified way, managed by eclipse libraries (imho best) or through different methods? I remember having the "xstream" xml library in use in some places -- definetely doing homebrewn persistence there.

**Comment by grthor** [comment]
The JCT workspace is moved from .jcryptool\ to its install directory. This means that a new JCT version no longer uses old, incompatible files. The problem has become less serious.
