### ISSUE TITLE
Frequency Analysis view garbled

### ISSUE THREAD

**Issue by yalla** [jcryptool/core#121]
When opening the frequency analysis view, you see three radio buttons:
* button3
* Simply give me a diagram and numbers
* Add more complex analysis capabiltities

I'm not quite sure, what 'button3' does (it's pretty much non-clickable), but the first two radio buttons are overlaid over each other.

Affects:
```
Version: 1.0.0
Build ID: 20180603 (weekly)
```
Screenshot:
![screenshot from 2018-06-07 10-06-33](https://user-images.githubusercontent.com/350047/41086702-1c5774c4-6a3b-11e8-98ac-cf86139b8bd2.png)

**Comment by grthor** [comment]
Hi Alexander,

thanks for reporting this issue. Can you give me some more information about your execution environment. Which os do you use? Which JRE Version?

Regards, Thorben

**Comment by yalla** [comment]
Sure:
```
$ java -version
openjdk version "1.8.0_171"
OpenJDK Runtime Environment (build 1.8.0_171-b10)
OpenJDK 64-Bit Server VM (build 25.171-b10, mixed mode)
$ uname -a
Linux zbox 4.16.13-300.fc28.x86_64 #1 SMP Wed May 30 14:31:00 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
$ cat /etc/redhat-release 
Fedora release 28 (Twenty Eight)
```

**Comment by yalla** [comment]
Additional: I looked at the console output and when I open the Frequency dialogue, the following error messages appear:
```
(JCrypTool:19945): Gtk-CRITICAL **: 12:03:57.020: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkRadioButton

(JCrypTool:19945): Gtk-CRITICAL **: 12:03:57.020: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkRadioButton

(JCrypTool:19945): Gtk-CRITICAL **: 12:03:57.102: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkSpinButton
```
Maybe that helps, too?

**Comment by yalla** [comment]
OK, I've found a workaround which I don't understand at all. First, I'm running Wayland and I found this reference to the GTK error above: https://bugs.eclipse.org/bugs/show_bug.cgi?id=486068#c7
So I tried:
```
$ export SWT_GTK3=0
$ ./JCrypTool 
Jun 07, 2018 1:11:29 PM java.io.ObjectInputStream filterCheck
INFO: ObjectInputFilter REJECTED: null, array length: -1, nRefs: 1, depth: 1, bytes: 70, ex: n/a
```
I opened the frequency dialogue and now neither the omnious button 3 is there, nor the error message occurs. Screenshot:
![screenshot from 2018-06-07 13-12-04](https://user-images.githubusercontent.com/350047/41096371-aee7f84a-6a54-11e8-8aeb-9ca249ce531b.png)
Honestly, I have no idea what I'm doing here, but it worked. I hope this helps you debugging things.

I leave it up to your to decide if this is a bug or if you want to simply close it.

**Comment by grthor** [comment]
Thanks for all the information about the bug 👍 . In the near future I will investigate the bug and then decide whether the issue remains open or closed.

Good that you have found a workaround and it works now.

Regards, Thorben

**Comment by simlei** [comment]
Just as a side note, I have had several issues with non-Java applications using GTK3 on my own personal computer. Somewhere I remember reading a rather exasperated "well and then you probably would try switching to gtk2 as version 3 probably is bugged with your distribution", along those lines.
