### ISSUE TITLE
jcryptool fails to launch in any operating system

### ISSUE THREAD

**Issue by 0xdcb** [jcryptool/core#128]
Tried downloading the latest stable jar and getting it to run in all of the following

Ubuntu 18.04 with JRE 8 or JRE 6
Kali 2018 W37 with JRE 8
OSX 10.13.6 JRE 8 or JRE 6
Win 10.17134 JRE 8 or JRE 6

All seven of these OS/JVM combos crash with various errors on launch, mostly unhandled error exceptions. 

Do I need to build some specific old VM instance to get this tool running? Or is the project abandoned at this point?

**Comment by grthor** [comment]
Hi, you do not need an old Java version. It works with Java 8 and even with Java 10.
Can you put the exception here?
Did you download the jcryptool here https://github.com/jcryptool/core/releases?

**Comment by 0xdcb** [comment]
I was downloading a (very old) wrong version, your github release works fine on win 10 and kali 

Sorry for the bad issue report!

**Comment by grthor** [comment]
No problem. Can you send me the link where you downloaded the old version? If it is one of our pages we can remove the file there or write an indication that there is a new version.
