### ISSUE TITLE
Install jcryptool on Macbook issue

### ISSUE THREAD

**Issue by trinhntt** [jcryptool/core#131]
I installed jcryptool on os 10.8.2 with java 1.8 but I still had an issue. Please help me to fix it.

See the log file
/Users/MacBook/Downloads/jcryptool.app/Contents/Eclipse/configuration/1546175902041.log.

**Comment by grthor** [comment]
Hello, can you upload the error log here so that I can look at it. Unfortunately I currently only see the file path to the error log. Simply drag the file into the comment box.

**Comment by trinhntt** [comment]
I cannot find the log file with the file path. Can you help me how to find it?

**Comment by trinhntt** [comment]
This is the log file.

**Comment by trinhntt** [comment]
This is the error log

**Comment by trinhntt** [comment]
This is the error log. Can you see it?

**Comment by trinhntt** [comment]
[1546175902041.log](https://github.com/jcryptool/core/files/2717749/1546175902041.log)

**Comment by grthor** [comment]
Hi, the error log indicates that you are using Java 1.6. Can you check your java configuration if you really use Java 1.8.

**Comment by trinhntt** [comment]
I installed jcryptool suceessfully after using Java 1.8. Thank you for supported.

**Comment by grthor** [comment]
Nice to hear that.
