### ISSUE TITLE
JavaFX support

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#133]
It would be nice to be able to mix in JavaFX-based controls into JCT -- but it should be explored first what implication this has on the Target Platform configuration, and whether it works on all platforms out of the box (we do not want to have builds fail or the product fail to launch by introducing this dependency)

Initial exploration on my [fork](https://github.com/simlei/core/tree/javafx) and of [tassadarius' fork](https://github.com/tassadarius/core/tree/javafx) has been done and will continue in a string of PRs:

https://github.com/simlei/core/pull/2
https://github.com/tassadarius/core/pull/1

At this point, it looks like we can use JavaFX-based UI elements in JCT in a development environment, using the [ef(x)clipse project and target definitions](https://www.eclipse.org/efxclipse/index.html).
On my machine (Linux/Ubuntu 16.04/Eclipse Photon 2018-09) I still have problems in pulling in JavaFX binaries at runtime. Still my most recent PR seems to work for @tassadarius (Windows/Eclipse Photon 2018-12)

1) get it running in development environment on my machine, find out what's stopping it now and if that would be a common source of problems for others on Linux.
2) If everything works smoothly in development, build a JCT product with Maven where single JavaFX-based plugin can be dropped into `$JCT_WORKSPACE/dropins`
3) Ascertain usefulness of JavaFX -- do we want this extra dependency in JCT?

if yes to 3)

4) Test 3) on all platforms (Windows 8,10, Ubuntu, OSX), on completion, merge w/ `core/develop` s.t. weekly builds get built like the separate JavaFX-build in 3)

"_ping_" @tassadarius for feedback

**Comment by simlei** [comment]
We're [moving to Java 11](https://github.com/jcryptool/core/issues/149) which is supposed to ship JavaFX. 

Tom Schindl seems to be the main man for javafx packaging and delivery, and seems to be active also in the Eclipse Forums. Here is his blog post on [OpenJDK 11, JavaFX](https://tomsondev.bestsolution.at/2018/08/04/supporting-openjfx-11-from-jdk11-onwards-in-efxclipse/)

He recommends shipping JavaFX with a JLink runtime environment ([good thing we use that now, too, TODO JLink issue](http://404.org)).

I do not know of any plugin that currently needs JavaFX support, so I suppose this can wait for after the release of v.1.0-final.

[other relevant eclipse forums discussion](https://www.eclipse.org/forums/index.php/t/1096912/)

**Comment by simlei** [comment]
Does anyone still need JavaFX?

**Comment by grthor** [comment]
I do not need it. It would be nice if the JCT would support it to be able to implement more beautiful graphics, but for now SWT is enough. 

If anyone needs JavaFx, he can implement it. However, since there is no specific demand for it, I would not invest the time in the implementation.

Would suggest to close this issue.

**Comment by simlei** [comment]
I agree; closing this until someone approaches with concrete JavaFX-related needs.
