### ISSUE TITLE
Cannot download from www.cryptool.org

### ISSUE THREAD

**Issue by sm8ps** [jcryptool/core#135]
Obviously I am too stupid to find a download link on https://www.cryptool.org/en/jct-downloads/stable. The relevant link seems to point to that page itself.
Sorry in advance if this is not the right place but I have not found any better.

**Comment by grthor** [comment]
Hi, this is the right place for all sorrts of issues. 
I would recommend you to use a weekly build. Weekly builds are also stable but have recently been heavily overhauled.
You can download them here https://github.com/jcryptool/core/releases.
I hope i could help you :)

**Comment by sm8ps** [comment]
Thanks, @grthor! In fact, I did download the weekly build and it is good to know that they are stable.
Nevertheless I can imagine that other users might hit the same difficulties. The problem is that the download link on the mentioned page does not seem to refer to a download page.

**Comment by sm8ps** [comment]
Thanks for considering my input!

**Comment by grthor** [comment]
Hi @sm8ps, we now fixed it.
