### ISSUE TITLE
Java 11 migration

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#149]
We are moving to Java 11 and are almost there.

@grthor's and my forks on the topic: https://github.com/grthor/core/tree/jre_bundle resp. https://github.com/simlei/core/tree/java11-migration

# Related issues

... The 2do for this issue is the status of these individual issues

- #151 javax xml bindings
- #TODO JLink packaging
- #120 Keystore
- #150 Target definitions and p2 sites for the JRE and javax xml bindings libraries

**Comment by simlei** [comment]
The most recent version from the JRE and other depending work is now always at https://github.com/jcryptool/core/tree/java11DevelopCandidate as per https://github.com/jcryptool/core/pull/154

All seems to work on Windows and Unix. On OS X, the product does not start likely due to misconfiguration of how the JRE is invoked in the p2 touchpoint. To fix this a Mac user needs to look into this.
It is necessary to work with [org.jcryptool.thirdpary](https://github.com/simlei/org.jcryptool.thirdparty). The process is scripted. This is detailed in https://github.com/simlei/org.jcryptool.thirdparty/wiki/Making-an-update-to-JRE-features,-locally-hosted

**Comment by grthor** [comment]
Our current status is that @charlottemagister has successfully built a Java 8 JCT on Mac and start it. Now she tries to build a Java 11 JCT from the Branches java11DevelopCandidate and java11DevelopCandidateCrypto.
The difference between @charlottemagister and @dschadow is that she uses an older MacOS, which exactly she uses I don't know.

**Comment by dshadow** [comment]
> Our current status is that @CharlotteMagister has successfully built a Java 8 JCT on Mac and start it. Now she tries to build a Java 11 JCT from the Branches java11DevelopCandidate and java11DevelopCandidateCrypto.
> The difference between @CharlotteMagister and @dshadow is that she uses an older MacOS, which exactly she uses I don't know.

Could you please explain why you mentioned me for the project? I have never used java at all

**Comment by grthor** [comment]
Sorry, my fault. I wanted to mark @dschadow. I will change my last comment.

**Comment by simlei** [comment]
This issue should be fixed. The last standing issue was, that OSX did not like our Java 11 JRE. It was a compound problem of problems that the following links touch:

- Java 11 has a bug for JNI start: https://bugs.openjdk.java.net/browse/JDK-8213362
- Symlinks have to be directly fixed in the feature's touchpoint.

Solution:

- Use JRE 13 for OSX (seems to be compatible to all our bytecode)
- magic line in osx-jre feature: https://github.com/simlei/org.jcryptool.thirdparty/blob/eac0caf0994234d4e0d71262b4758f6d687fc493/ projects/org.jcryptool.thirdparty.jre/org.jcryptool.thirdparty.jre.macosx.feature/p2.inf#L5 based on something I found on the web, but where was unlucky enough that the paths had already changed since that was posted.

To explain the problem and solutions in more detail is for another time.
