### ISSUE TITLE
JCT editor text selection not working since WB september/october

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#156]
# Overview

The text editor crashes when selecting text.

via @grthor the error was probably introduced between sep. 28 and oct. 05.
> Der Fehler ist einfach irgendwann aufgetaucht. 
> Ich habe das gerade mal eingegrenzt, indem ich die letzten WBs durchgetestet habe. Im WB vom 
> 05.10.19 tritt der Fehler das erste Mal auf, im WB vom 28.09. funktioniert der Editor noch.

The issue is probably best pinpointed through identifying the exact commit that introduced it, and looking at the diffs.

Dabei sollte man beachten:

- `core` und `crypto` sollten zusammen ausprobiert werden. zB mit dem aktuellen `crypto` repo geht der `core` von September nicht bei mir zu bauen, da `crypto` schon neueren Code erwartet.
- Deshalb: immer Paare von revisionen aus core und crypto auschecken und notieren.
- Der build in `core/org.jcryptool.releng` bezieht sich implizit auf das `core/../crypto` Verzeichnis, deshalb darauf achten dass man die jeweiligen repos richtig zueinander positioniert.

Weiter unten verzeichne ich die möglicherweise betroffenen Revisionen.

**Comment by simlei** [comment]
# Revisions

## Core revisions

```
[b4] 399f170d        Thorben Groos   Wed Oct 2 11:15:20 2019 +0200   Workspace location 
796653e7        Thorben Groos   Wed Oct 2 11:09:35 2019 +0200   Fixed Problem with 
[b3] f3fef988        Dominik Schadow Sun Sep 29 09:20:19 2019 +0200  Added missing langu
[b2] 3832122c        Dominik Schadow Sun Sep 29 09:00:42 2019 +0200  Updated to latest E
78e9090d        Dominik Schadow Sun Sep 29 08:57:40 2019 +0200  Updated to latest B
[b1] 66379535        Thorben Groos   Sat Sep 28 11:32:47 2019 +0200  Removed hard coded 
```

## Crypto revisions

```
[b4] 25e421dd        Thorben Groos   Sat Oct 5 17:17:44 2019 +0200   Merge remote-trackin
9ea54ae9        Thorben Groos   Sat Oct 5 17:17:06 2019 +0200   Removed tag 
1ceaff35        Thorben Groos   Fri Oct 4 21:54:51 2019 +0200   Merge pull request #
8f811e60        Michael Altenhuber      Thu Oct 3 20:00:47 2019 +0200   Refactoring 
6165d9eb        be4     Wed Oct 2 01:21:21 2019 +0200   JCT online help for the SPHI+
0c32f53c        Thorben Groos   Mon Sep 30 10:53:47 2019 +0200  Merge remote-trackin
6ab5876b        Thorben Groos   Mon Sep 30 10:53:11 2019 +0200  Fixed Typos
3419bd13        be4     Sun Sep 29 18:05:22 2019 +0200  JCT online help for Certific
7c53a73a        Dominik Schadow Sun Sep 29 09:07:16 2019 +0200  Organized imports
[b2,b3] a6518c37        Dominik Schadow Sun Sep 29 09:06:46 2019 +0200  No need to inject wi
1dde0afa        Dominik Schadoself instantiated variable required
[b1] 37003b22        Thorben Groos   Sat Sep 28 11:33:23 2019 +0200  Removed hard coded v
```

**Comment by simlei** [comment]
Das sind schon mal einige automatisch generierte Builds, Querschnitte der Revisionenrange oben:
https://www.dropbox.com/sh/tbjkdcowkbhz135/AAAlhMxVvAPFTWSIA-IusVXSa?dl=0

```
.
└── builds
    ├── 3832122c_a6518c37    [b2]       
    ├── 399f170d_25e421dd    [b4, "latest"]
    ├── 66379535_37003b22    [b1, "earliest"]
    └── f3fef988_a6518c37    [b3]
```

**Comment by grthor** [comment]
I was able to find the commit that caused the exception. It is the commit that updates from Eclipse Release 2019-06 to Eclipse 2019-09 https://github.com/jcryptool/core/commit/3832122cff35a03dc9d5bd84a541d0d95707ca68 (Migration to Eclipse 2019-09)
With commit https://github.com/jcryptool/core/commit/78e9090d746876b917e28314df21c0cd699e61e9 (Update to latest Babel update site) the text editor works.

I tested both core commits with https://github.com/jcryptool/crypto/commit/7c53a73a29fb2c89a0e33e76459a6ed9c874570a from the same day (29.09.2109).

**The problem occurs after the migration to Eclipse 2019-09.**

**Comment by grthor** [comment]
The text editor worked, after I switched the target platform back to 2019-06.

**Comment by simlei** [comment]
I'm for switching the version to 2019-06 then in our `develop` HEAD, to not have this bug in the weekly builds. But we should stay on 2019-06 forever because of this, so we should investigate if we can do something about it in the JCT code base. I believe, we have JCT-specific implementation regarding the text editor which could well have become incompatible to the newest eclipse releases: https://github.com/jcryptool/core/tree/develop/org.jcryptool.editor.text

Also, #153 was solved based on 2019-09 and for that, I have compiled parts of eclipse based on that version. I'd rather avoid having to replay that against 2019-06.

I'd leave this issue open, remove the bug and showstopper labels, perhaps change the issue title to "incompatibility of text editor to eclipse release 2019-09", and keep an eye on it.

**Comment by grthor** [comment]
I see it the same way you do. We shouldn't be based on an "outdated" Eclipse 2019-06. Also in terms of #153 we should use Eclipse 2019-09.
But now I'm migrating back to 2019-06 to make the text editor work again.

You're right, we have custom editors that may have become incompatible. I'll take a look at that in the next few days.

I'll let you know when I've found something or can't get any further.

**Comment by grthor** [comment]
@dschadow just migrated with https://github.com/jcryptool/core/commit/b3f96269a1c7f370f80a69e4a4f245c66edf9d0e to Eclipse 2019-12. 

We should check the texteditor functionality in the next WB. Maybe the problem fixed itself. Elsewhere we should migrate back to Eclipse 2019-06.

**Comment by simlei** [comment]
This is solvable by supplying a PreferenceStore in the JCT Text Editor Implementation. We never touched this; however, Eclipse Code is now accessing the preference store at one point without checking for null. We can bypass it by just supplying an empty `PreferenceStore()` instance. Minimally tested, will do a PR later when it's all clear on my build environment.

**Comment by simlei** [comment]
PR #164 pushes JCT to the 2019/09 target platform. Any Issues in the next WB, please comment.

**Comment by grthor** [comment]
Can we directly migrate further to Eclipse 2019-12? Then we will will use the current Eclipse Version. @dschadow done this last month but I migrated back because the Editor wasn't working.

**Comment by simlei** [comment]
No, the incoming solution to #153 is built on 2019/09. Won't try to re-build that on 2019/12 or later until the v1.0 is released. I.e. v1.0 will be based on 2019/09

**Comment by grthor** [comment]
Ok, i forgot that. 
We should then try to migrate after the release. 
Can we suggest the Eclipse fix so that it would be included in any version of Eclipse? That would have several advantages for us. A: we wouldn't have to worry about maintenance anymore. B: we could remove the update site we use to bring this fix into JCT.

**Comment by simlei** [comment]
Yes, the plan is to get the causes for workarounds and custom builds fixed
upstream at some time. For this issue however it seems completely fixed
until they introduce another non-null-check code.
