### ISSUE TITLE
Implementing a Quick Access Bar 

### ISSUE THREAD

**Issue by grthor** [jcryptool/core#162]
It would be cool if the JCT had a Quick Access Bar, just like the Eclipse IDE. 

![draft](https://user-images.githubusercontent.com/20046726/71589953-0e308080-2b27-11ea-88ef-1c704dcf58a0.PNG)

Since such a Quick Access Bar already exists in Eclipse, you might be able to learn how to program something like that.

@tassadarius is currently working on this task.

**Comment by tassadarius** [comment]
Eclipse IDE itself uses as search bar (at the moment in the newer version it's a button) the QuickAccess feature. It can be accessed by using the extension Point `org.eclipse.ui.window.quickAccess`.

An example if you want to implement it by adding the following extension point to
`org.jcryptool.core/plugin.xml`

```xml
<menuContribution
            allPopups="false"
            locationURI="toolbar:org.jcryptool.core.toolbar">
         <command
               commandId="org.eclipse.ui.quickAccess"
               icon="PATH/TO/ICON.png"
               style="push">
         </command>
</menuContribution>
```

## Example:

![quick_access3](https://user-images.githubusercontent.com/22643766/77805888-64a84f00-7083-11ea-8d61-efefb28baa49.gif)

## Problems / TODO

 * [ ] Eclipse IDE positions the search button more prominently, we should too, do that
 * [x] Building with maven does currently not work
 * [ ] Filter out internal commands (if possible)

**Comment by tassadarius** [comment]
### Solved with Commit https://github.com/jcryptool/core/commit/d0c3e72f34601123dd30b7b7686e507e128c57e7

![quick_access](https://user-images.githubusercontent.com/22643766/77822119-27c67180-70f0-11ea-896f-a6965ca231d9.png)

### Added a QuickAccess-Improvement Issue: [#184]
