### ISSUE TITLE
Perspective layout / workbench misbehavior (e.g. views not restorable)

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#176]
There is sporadic misbehavior of the view system / the workbench, most commonly when dealing with maximized views (e.g. visualizations) and their hidden sibling views. Restoring them sometimes does not work, resetting the perspective is the only way forward. 

How-to-reproduce instructions is still needed to tackle this problem.

**Comment by grthor** [comment]
@be4 done some investigations and created a documentation when the problem occurs.

For this he created 5 sequences, starting again and again with an empty data directory.
Sequence E (p. 19-21) is the shortest. 2 more times he could trigger the error.

[Feedback_KeinZurückzuEditoren.pdf](https://github.com/jcryptool/core/files/4328689/Feedback_KeinZuruckzuEditoren.pdf)

**Comment by grthor** [comment]
Tested by @be4 and me. Both could not reproduce anymore. 

Maybe the migration to Eclipse 2020-06 fixed it.
