### ISSUE TITLE
Unable to update maven configuration for Bouncycastle and Flexiprovider

### ISSUE THREAD

**Issue by grthor** [jcryptool/core#181]
The maven configuration for the Bouncycastle and Flexiprovider projects cannot be updated. This leads to the initial setup of the IDE. 

The following error message is displayed.
![GIF 20 03 2020 18-32-13](https://user-images.githubusercontent.com/20046726/77190331-55506100-6ad9-11ea-9485-5953d85df668.gif)

![image](https://user-images.githubusercontent.com/20046726/77190759-1ff84300-6ada-11ea-8063-ead7fb1ae636.png)

I found some similar errors on the internet, but could not solve the problem with the given solutions.
- https://stackoverflow.com/questions/10838109/eclipse-build-path-nesting-errors
- http://www.programmersought.com/article/89071627792/

There is a workaround but I can not remember it. @simlei do you remember how we fixed the problem on my pc?

We should definitely find the root of the problem, the workaround we used is not practical and keeps possible new developers from working on JCT.

**Comment by simlei** [comment]
I am not experiencing this problem on my machine. Does it persist with a fresh workspace?

> The maven configuration for the Bouncycastle and Flexiprovider projects cannot be updated.

What have you been trying to do?

> There is a workaround but I can not remember it.

Sorry, I only vaguely remember seeing this error.

**Comment by grthor** [comment]
Yes, it occured while I tested the new getting-starteed tutorial. I receive the error dialog on my laptop and pc.

On my laptop I have a complete fresh eclipse installation with no old files (neither git, nor m2 or other files.)

**Comment by grthor** [comment]
The problem was solved by removing the src folders from the bundle class path.

The Maven build is running.
