### ISSUE TITLE
Weeklybuild 29-03-2020 fails to start on Linux (JVM error 13)

### ISSUE THREAD

**Issue by tassadarius** [jcryptool/core#185]
Trying to run weekly build [29-03-2020](https://github.com/jcryptool/core/releases/tag/Weekly-Build-29-03-2020) on Linux throws the following error:

![error_msg](https://user-images.githubusercontent.com/22643766/78424096-6d90b600-766b-11ea-9a7f-e83159e2d9b9.png)

Machines the bug occured on:
 **1)**
 * Distribution Manjaro
 * Kernel: 5.4.28-1
 * JVM: Shipped JVM

**2)**
 * Distribution Manjaro
 * Kernel: 5.5.13-1
 * JVM: Shipped JVM
----

### Further info

I do not know if or where the shipped JVM stores logs

This does neither occur on Windows nor on build [21-03-2020](https://github.com/jcryptool/core/releases/tag/Weekly-Build--2020-03-21).

The double slashes in the paths seem suspicious, but it turns out they are added by the error window. If you run it from comand line with definetly correct path it turns out the same.

### Workarounds

In `JcrypTool.ini` Changing the `-vm` argument from the default path `features/org.jcryptool.thirdparty.jre.linux64.feature_11.0.5.009/jre/bin/java` to system's java (if install) may fix the problem

**Comment by simlei** [comment]
Thanks!
This is probably due to that particular release being built on @grthor 's machine. I guess a windows-based build is no good.

**Comment by simlei** [comment]
I have the same problem but have had to run an additional `chmod +x ./JCrypTool`. The current build (Travis CI) works for me.

Seems all the non-windows-file-system things look wrong. I don't even think Windows is to blame, but the Maven Tycho plugin not being well tested for cross-platform builds under Windows.

**Comment by grthor** [comment]
Are there any other reasons why this issue should remain open. I think we have found the reason for the malfunction, namely that the WB was built on a Windows PC.
If not, I would like to close it.
