### ISSUE TITLE
Call me naive regarding this question about a Plugin Designer tool or editing a plugin for Cryptools

### ISSUE THREAD

**Issue by Stellarwest** [jcryptool/core#191]
I'm not really quite up to speed with the Cryptools 2.1 yet, however I'm fascinated with this program.  I have spent 96 hours going over it already trying to tweak cvs files, fonts and the Morse code to no avail for my ciphers requirements.  My problem is that I'm working with an exotic cipher named the Voynich Manuscript.  I have a theory that the Voynich Manuscript was published in 1910 as a hoax on old calfskin and the inks he manufactured as he was a chemist.

[https://www.jasondavies.com/voynich/#f57v/0.591/0.406/2.50](url)

Here is my dumb question, can I edit a morse.cwm file to change the Morse code for my spefications?  **Or better yet has Cryptools released a plugin designer application?**  I really want to tweak the Morse Code.

For anyone who would like to see my work on the Voynich Manuscipts Cipher here is a link. 

http://voynich.net/forum/viewtopic.php?f=5&t=15&sid=69728b7082bea457aafa3d66ef28f14d

My exotic Morse code cipher to Voynich Glyphs:

https://voynichman.freeforums.net/thread/51/python-code-morse-italian

**Comment by ct-online** [comment]
You posted your question to the JCrypTool Issue Tracker. As this question is releated to CrypTool 2, I forwarded this to the CT2 group. Hope they can help. Do you have an email address so they can send you the answer?

**Comment by grthor** [comment]
Hi @Stellarwest,

heard the CT2 team is taking care of your request. If it is all right with you I would close this issue.

Best regards,
Thorben

**Comment by grthor** [comment]
I assume the problem could be fixed and will close the issue.
