### ISSUE TITLE
Algorithms view: Authentication codes - HMac and TwoTrackMac not working

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#2]
All entries in the Authentication codes - HMac and TwoTrackMac group are not working. A double click does not open a wizard nor does it add an entry in the Operations view. There seems to be a problem with the current version of the algorithms.xml.

**Comment by simlei** [comment]
Could not reproduce, likely that the algorithms.xml problem is fixed by now. The only HMac implementation (HMacMD5) works as far as I can tell.
