### ISSUE TITLE
Small tutorial on how to use the algorithm perspective

### ISSUE THREAD

**Issue by grthor** [jcryptool/core#202]
Since the algorithm perspective is difficult to understand for new users at the beginning, a tutorial for the operation should be displayed directly.

I suggest that this tutorial is displayed in the middle field (where the sample text is located) or in the lower left corner (where the context help is usually displayed). These are both clearly visible areas.

<img width="852" alt="Unbenannt" src="https://user-images.githubusercontent.com/20046726/80604470-0f6cae00-8a32-11ea-9fb4-b4faec3b9036.PNG">

I think one could implement such a tutorial either by using a custom plugin which is displayed at one of the two places when opening the algorithm perspective, or by using a context help entry which is displayed when opening the perspective.

Texts and screenshots for the tutorial are already available, in the [user presentation](https://www.cryptool.org/images/jct/pdf/JCrypTool_Praes_de.pdf) on page 9 and 77 to 82. Especially the order on page 81 is interesting for new users.

**Comment by grthor** [comment]
**I want to give you an update on how the algoritm introduction should look like and how the project is going.**

## The plan

I decided to add the introduction in the middle area of the JCT, the so called "editor area". There is the most space to display screenshots and text. The introduction should be displayed in an own tab (more professional: view) next to the editor. It should have the following structure:

![image](https://user-images.githubusercontent.com/20046726/85232403-f0b9e080-b3fe-11ea-8077-06965286beaa.png)

The goal for the introduction is to have as little user interaction as possible and to make the plugin as user-friendly as possible. Therefore the plugin is kept very simple. It should consist of an upper part, where screenshots give step-by-step instructions and a lower part where there should be a textual tutorial.

The screenshots should be displayed in a slideshow. The slideshow should run automatically. A user should be able to view the previous screenshot by clicking on the left half of the current screenshot and the following screenshot by clicking on the right half of the current screenshot.

So much for the theory 😄 now comes the interesting part how the project is going.

## The  current status
The introduction is shown automatically if the user switches to the algorithm perspective in the middle area of the JCT as it was plannend. This task was quite tricky because Eclipse does not want  to open views in the so called editor area. Only editors should be opened there. But with a little effort, it worked. Here is a Screenshot how it looks after a user switched to algorithm perspective.

![image](https://user-images.githubusercontent.com/20046726/85232690-2c55aa00-b401-11ea-8371-4fe8ea33aa1b.png)

The user can also open the view via the "Window" -> "Show View" -> "Introduction".
![image](https://user-images.githubusercontent.com/20046726/85232716-6aeb6480-b401-11ea-8f5b-297a63f19452.png)

As already mentioned, the introduction is opened every time a user switches to the algorithm perspective. This can be annoying if you do not need it. So I added a "Do not show again" checkbox in the bottom right corner (like in the Eclipse Intro). This setting can also be done in the "Preferences" section of the JCT.

![image](https://user-images.githubusercontent.com/20046726/85232760-d2091900-b401-11ea-8370-71768a0ad2ad.png)

The slideshow in the upper part of the plugin shows already images (thanks to [SWT Transition Widget](https://www.eclipse.org/nebula/widgets/stw/stw.php)), but a user can not switch between images by clicking on the left or right side of the plugin. I am currently working on this.

The step after adding the possibility to switch left and right is adding content to the plugin. Either I copy the screenshots for operating the perspective from the user documentation or make my own. Then I write/copy a text that describes the operation of the perspective.

**I plan to finish the plugin next week.**

Sorry for the long post...

I think the plugin will be useful and later help many people to get started with this perspective!

**Comment by be4** [comment]
Herr Groos,

großartig -- gut, dass Sie an all diese Dinge dachten.

Hier noch ein wenig formales Feedback:

- Schreibweise im Deutschen:
   Algorithmen-Perspektive  [mit Bindestrich]

Statt
   - Fenster -> Sicht anzeigen -> Instruction
besser
   - Fenster -> Sicht anzeigen -> Instruktion Algorithmen-Perspektive

Gruß und danke, BE



Am 21.06.2020 um 21:04 schrieb Thorben Groos:
> **I want to give you an update on how the algoritm introduction should look like and how the project is going.**
>
>
>
> ## The plan
>
>
>
> I decided to add the introduction in the middle area of the JCT, the so called "editor area". There is the most space to display screenshots and text. The introduction should be displayed in an own tab (more professional: view) next to the editor. It should have the following structure:
>
>
>
> ![image](https://user-images.githubusercontent.com/20046726/85232403-f0b9e080-b3fe-11ea-8077-06965286beaa.png)
>
>
>
> The goal for the introduction is to have as little user interaction as possible and to make the plugin as user-friendly as possible. Therefore the plugin is kept very simple. It should consist of an upper part, where screenshots give step-by-step instructions and a lower part where there should be a textual tutorial.
>
>
>
> The screenshots should be displayed in a slideshow. The slideshow should run automatically. A user should be able to view the previous screenshot by clicking on the left half of the current screenshot and the following screenshot by clicking on the right half of the current screenshot.
>
>
>
> So much for the theory 😄 now comes the interesting part how the project is going.
>
>
>
> ## The  current status
>
> The introduction is shown automatically if the user switches to the algorithm perspective in the middle area of the JCT as it was plannend. This task was quite tricky because Eclipse does not want  to open views in the so called editor area. Only editors should be opened there. But with a little effort, it worked. Here is a Screenshot how it looks after a user switched to algorithm perspective.
>
>
>
> ![image](https://user-images.githubusercontent.com/20046726/85232690-2c55aa00-b401-11ea-8371-4fe8ea33aa1b.png)
>
>
>
> The user can also open the view via the "Window" -> "Show View" -> "Introduction".
>
> ![image](https://user-images.githubusercontent.com/20046726/85232716-6aeb6480-b401-11ea-8f5b-297a63f19452.png)
>
>
>
> As already mentioned, the introduction is opened every time a user switches to the algorithm perspective. This can be annoying if you do not need it. So I added a "Do not show again" checkbox in the bottom right corner (like in the Eclipse Intro). This setting can also be done in the "Preferences" section of the JCT.
>
>
>
> ![image](https://user-images.githubusercontent.com/20046726/85232760-d2091900-b401-11ea-8370-71768a0ad2ad.png)
>
>
>
> The slideshow in the upper part of the plugin works shows already images, but a user can not switch between images by clicking on the left or right side of the plugin. I am currently working on this.
>
>
>
> The step after adding the possibility to switch left and right is adding content to the plugin. Either I copy the screenshots for operating the perspective from the user documentation or make my own. Then I write/copy a text that describes the operation.
>
>
>
> **I plan to finish the plugin next week.**
>
>
>
> Sorry for the long post...
>
>
>
> I think the plugin will be useful and later help many people to get started with this perspective!
>
>
>
>
>

**Comment by grthor** [comment]
It is finished 🎉
