### ISSUE TITLE
Document org.jcryptoool.thirdparty integration

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#204]
Thirdparty library support is getting more and more mature, now providing the basis for:

- [Java XML bindings for Java 8 legacy code packaging](https://github.com/simlei/org.jcryptool.thirdparty/tree/master/projects/org.jcryptool.thirdparty.m2bundle.jaxb)
- [Standalone JRE packaging](https://github.com/simlei/org.jcryptool.thirdparty/tree/master/projects/org.jcryptool.thirdparty.jre)
- [Packaging of custom patches for the Eclipse Platform](https://github.com/simlei/org.jcryptool.thirdparty/tree/master/projects/org.jcryptool.thirdparty.platformpatches)
- [Support for packaging any Maven-Central-hosted library as JCT target platform dependency, with sources](https://github.com/simlei/org.jcryptool.thirdparty/blob/a267921bf5807f7d433d56bb2337cbe849acbb90/releng/org.jcryptool.thirdparty.m2bundle.p2/pom.xml#L26-L47)
- [Durian (Library) for SWT repackaging](https://github.com/simlei/org.jcryptool.thirdparty/tree/master/projects/org.jcryptool.thirdparty.m2bundle.durian-swt) (https://github.com/diffplug/durian-swt)

This is a major step up from the manual packaging of dependencies -- e.g. as workspace projects or as JARs in individual bundles -- because of the high degree of reliability and of following Eclipse best practices. Any dependency can be resolved through `MANIFEST.MF` `Require-Bundle` instructions. Most importantly, though, these artifacts _are subject to the p2-based update delivery to existing JCT installations and can facilitate the "agree to these licenses" UI, easing the burden of informing the user about licensing_.

Because of the critical role of these dependencies, the Maven-based mechanism behind this integration must be **documented** properly; this also goes for the release process of updating or adding such dependencies.

**Comment by grthor** [comment]
Documentation is really important, otherwise no one will use it afterwards, because no one will understand it. That would be too bad.

I have one more point, which also has to do with the thirdparty-repository. 
I think it makes sense to add the thirdparty-repo as a jcryptool-repository, like core, crypto, tests, ... Then again all things are bundled in one place and not distributed on private forks.

**Comment by simlei** [comment]
> I think it makes sense to add the thirdparty-repo as a jcryptool-repository, like core, crypto, tests, ... Then again all things are bundled in one place and not distributed on private forks.

Definitely. I think the best time to do so is when we finally move hosting the p2 repository not on github pages -- right now, it is done this way in my repo and it blows its size up to considerable propertions which any person that clones it to work on it has to keep on their hard drive.

**Comment by simlei** [comment]
> > I think it makes sense to add the thirdparty-repo as a jcryptool-repository, like core, crypto, tests, ... Then again all things are bundled in one place and not distributed on private forks.
> 
> Definitely. I think the best time to do so is when we finally move hosting the p2 repository not on github pages -- right now, it is done this way in my repo and it blows its size up to considerable propertions which any person that clones it to work on it has to keep on their hard drive.

The above is done.

Documentation is there now: 
https://github.com/jcryptool/org.jcryptool.thirdparty/blob/master/README.md
https://github.com/jcryptool/org.jcryptool.thirdparty/wiki/Locally-publish-and-use-%60org.jcryptool.thirdparty.libraries.p2%60-changes
... and has been proven effective in the context of getting bouncycastle into the target platform as per https://github.com/jcryptool/org.jcryptool.thirdparty/commit/9f4167d092dba2f327ef115fedfdb1b4de7ef733
