### ISSUE TITLE
Oomph installer for JCT IDE

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#209]
Preliminary tests for the Oomph installer have been successful -- using [this guide](https://github.com/jcryptool/core/wiki/Getting-started-with-programming-for-JCrypTool----with-Oomph) Eclipse is installed almost automagically, the git repos are cloned, the projects are imported*, the target platform resolved, necessary plugins installed*.

However, there is even more room for improomphement:
1) In some cases I have seen that some projects are skipped during import. I suspect eclipse hiccups here. I'm not sure this can be fixed, but have not investigated it. In one case, they were by name:
  - the "platformpatches" project
  - the "3rdparty jre" project
  - the "functionlistgen" project
  - the "core" project
2) We do not install all the plugins from the [old guide](https://github.com/jcryptool/core/wiki/Getting-started-as-a-JCrypTool-Developer) yet. Namely, checkstyle and findbugs. I do not know of any one that has these currently installed however. I do kind of not dare to install them myself because I think they would report a ton of style violations and find even more probable bugs than is feasible right now to handle.
3) The default JRE and the default Compiler compliance level should be set to "11". This is because right now we already have Java 10 constructs like 'var' in our code where we are getting red squiggly marks from Eclipse even though the JRE would compile successfully.

None of this seems critical right now (*1)* could be solved with a hint in the installation guide and does not occur every time). The "download, install & follow instructions" seems to be nearing a 1-click experience, not counting "Accept licenses" dialogs.

But some time down the road we should be able to really get there; the points above should be a start in doing so.

For the record, the IDE installation file is located here: https://github.com/jcryptool/core/blob/core-infrastructure/org.jcryptool.core/ide/JCTIDEConfiguration.setup

**Comment by grthor** [comment]
To point 2: I also think that nobody uses the plugins checkstyles and findbugs anymore. So I would adapt the guide to the real/current workflow and remove them.

PS Findbugs is dead by the way, its successor is SpotBugs https://spotbugs.github.io/

**Comment by simlei** [comment]
Replaced the old "Getting Started" guide, closing this issue.
