### ISSUE TITLE
Twofish in jcryptool ?

### ISSUE THREAD

**Issue by akj0929** [jcryptool/core#210]
Is there any way to utilize twofish encryption/decryption algorithm and we could find stats like encryption time, cipher text size and throughput for each encryption/decryption process.

or 

is there any way to extend cryptool 2 UI to my codebase in eclipse ?

**Comment by be4** [comment]
Hello Kumar.

JCT contains the Twofish cipher within the Algorithm perspective (as
part of the block ciphers).

Currently there are no stats about throughput for each
encryption/decryption process built into JCT. Normally such measures are
done at the commandline, like with openssl or with BouncyCastle as
mentioned above.

What do you mean with "cipher text size"? There is no limit in the input
file size for modern block ciphers. And the output has the same length
as the input -- rounded up to the next multiple of a block size (which
is neglectable).

Could you please explain in more detail what you want to do and what you
mean with your "codebase in eclipse"?

Best regards, BE



Am 16.06.2020 um 13:58 schrieb aakash kumar:
> Is there any way to utilize twofish encryption/decryption algorithm and we could find stats like encryption time, cipher text size and throughput for each encryption/decryption process.
>
> or 
>
> is there any way to extend cryptool 2 UI to my codebase in eclipse ? 
>
