### ISSUE TITLE
Check thirdparty libraries and their licenses

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#214]
Before v1.0 we should make sure we are in the clear w.r.t. thirdparty library licenses (although I think we always checked before introducing a depenency). As an open source project we don't have to care about commercial-use clauses; still, there are other concerns than commercial use.
Also, we should make sure that the user sees license agreements and potentially agrees to them where necessary (e.g. through the eclipse-RCP built in mechanism).

Possibly we may want to acknowledge the thirdparty libraries used in our about page, even if this is not required by the license.

This list should be expanded (note that packages contributed *directly* via the target platform, i.e. with OSGi/p2 manifests, already note their licenses, so they don't have to be listed here):

- [x] All libraries that reside in https://github.com/simlei/org.jcryptool.thirdparty/tree/master/projects
- [x] [MathJax](http://docs.mathjax.org/en/latest/misc/faq.html#faq-license) (used here: [o.j.core.help](https://github.com/jcryptool/core/tree/develop/org.jcryptool.core.help/javascript))
- [x] <Code we copied to and package through source/resource folders of individual plugins>

**Comment by grthor** [comment]
Ich habe alle Plugins durgeschaut. Dabei habe ich auf 
- Packages, welche nicht jcryptool im Namen enthalten, (bspw. org.sourceforge. ... anstatt org.jcryptool.core. ... )
- Referenced Libraries,
- Ordner names "lib"

geschaut. Damit sollte eine Großteil des externen Codes abgedeckt sein. 

### Eclipse 
| Package | License|
|----------|--------|
|Eclipse Platform | EPL 2.0|
|Eclipse Platform Launcher Executables | EPL 2.0
|Eclipse RCP | EPL 2.0|
|Eclipse RCP SDK | EPL 2.0|
|Equinox Core SDK | EPL 2.0|
|Equinox p2, SDK | EPL 2.0|
|GEF (MVC)  | EPL 1.0|
|Zest SDK |EPL 1.0|

### Babel
| Package | License|
|----------|--------|
|Babel language pack for datatools in german | EPL 2.0|
|Babel language pack for eclipse in german | EPL 2.0|

### JREs
| Package | License|
|----------|--------|
|AdoptOpenJDK JREs | GPLv2+CE |

### Thirdparty packages in jcryptool/core
| Package | License|
|----------|--------|
|com.lowagie.itext | Problematisch! https://kb.itextpdf.com/home/it5kb/faq/can-i-bundle-itext-with-my-non-commercial-software schreibt, dass, wenn man Software unter einer EPL Lizenz verteilt (wie das JCT), diese nicht mit der AGPLv3 Lizenz kompatibel ist.|
|  com.thoughtworks.qdox   | APACHE LICENSE, VERSION 2.0| 
|  com.thoughtworks.xstream |  BSD licenses|
| de.flexiprovider | The Core Provider module is LGPL licensed, the EC and the NF Provider modules are GPL licensed. |
| net.sourceforge.codec | Keine Lizenz gefunden; Möglicherweise gilt folgende Lizenz, falls dieses Package mit dem Flexiprovider zusammenhängt: Licensing of the codec package is subject to the SeMoA license which is similar to the LGPL.|
| net.sourceforge.javahexeditor | GNU GPL v2 |
| org.apache.commons.cli | APACHE LICENSE, VERSION 2.0 | 
| org.bouncycastle | Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is furnished to do so, subject to the following conditions: |
| org.jdom | JDOM is available under an Apache-style open source license, with the acknowledgment clause removed. This license is among the least restrictive license available, enabling developers to use JDOM in creating new products without requiring them to release their own products as open source. This is the license model used by the Apache Project, which created the Apache server. The license is available at the top of every source file and in LICENSE.txt in the root of the distribution. | 

### In Packages kopierter Code
| Package | License|
|----------|--------|
 | MathJAX in org.jcryptool.help |  APACHE LICENSE, VERSION 2.0 |
| tocbot in org.jcryptool.help | MIT License |
| Nebula STW in org.jcryptool.introduction | EPL 2.0 |
| org.eclipse.wb.swt in org.jcryptool.crypto.ui| EPL 1.0 |
| com.github.aelstad.keccakj.* in org.jcryptool.visual.sphincsplus | APACHE LICENSE, VERSION 2.0|
| com.keypoint in org.jcryptool.visual.verifiablesecretsharing.lib | LGPL |
| org.jfree in org.jcryptool.visual.verifiablesecretsharing.lib | LGPL |

**Comment by grthor** [comment]
Zusammengefasst haben wir einen Mix aus EPL 2.0, EPL 1.0, GPLv2, GPLv2 mit Classpath Extension, LGPL, GPL, AGPLv3, BSD, MIT, Apache License v2 und zwei nicht standardisierten Lizenzen. 

Die beiden nicht standardisierten Lizenzen habe ich mir angeschaut, diese sind sehr frei und beschränken uns nicht.

@be4 ich denke Sie haben die meiste Ahnung welche Lizenzen miteinander kompatibel sind. Können Sie einen Blick darauf werfen und einschätzen, ob der Lizenzmix so zulässig ist?

**Comment by simlei** [comment]
Alle Libraries, die durch org.jcryptool.thirdparty bis Release 1.0 ausgeliefert werden:
Alle Lizensen sind kompatibel nach bisherigem Dafürhalten.

| Package | License| Link |
|----------|--------|-------|
org.glassfish.jaxb | EPL | |
javax.xml.bind | CDDL 1.1, GPL 1.1 | https://oss.oracle.com/licenses/CDDL+GPL-1.1|
org.glassfish.jaxb | CDDL 1.1, GPL 1.1 | https://oss.oracle.com/licenses/CDDL+GPL-1.1|
openjdk: The GNU General Public License (GPL)|
com.google.guava:guava | Apache 2.0 | https://github.com/google/guava/blob/master/COPYING|
com.google.code.gson:gson | Apache 2.0 | https://github.com/google/gson/blob/master/LICENSE|
com.google.dagger:dagger | Apache 2.0 | https://github.com/google/dagger/blob/master/LICENSE.txt|
com.google.dagger:dagger-compiler | Apache 2.0 | https://github.com/google/dagger/blob/master/LICENSE.txt|
org.huoc:cofoja | LGPL-3.0 | |
org.jcryptool.thirdparty:org.jcryptool.thirdparty.m2bundle.durian-swt | Apache 2.0 | https://github.com/diffplug/durian/blob/master/LICENSE|
org.jcryptool.thirdparty:org.jcryptool.thirdparty.m2bundle.durian-swt-os | Apache 2.0 | https://github.com/diffplug/durian/blob/master/LICENSE|
com.diffplug.durian:durian-rx | Apache 2.0 | https://github.com/diffplug/durian/blob/master/LICENSE|
io.reactivex.rxjava2:rxjava | Apache 2.0 | https://github.com/ReactiveX/RxJava/blob/3.x/LICENSE|
com.diffplug.durian:durian-core | Apache 2.0 | https://github.com/diffplug/durian/blob/master/LICENSE|
com.diffplug.durian:durian-collect | Apache 2.0 | https://github.com/diffplug/durian/blob/master/LICENSE|
com.diffplug.durian:durian-concurrent | Apache 2.0 | https://github.com/diffplug/durian/blob/master/LICENSE|
com.diffplug.durian:durian-reflect | Apache 2.0 | https://github.com/diffplug/durian/blob/master/LICENSE|
com.diffplug.durian:durian-io | Apache 2.0 | https://github.com/diffplug/durian/blob/master/LICENSE|
org.functionaljava:functionaljava | BSD 3|
org.immutables:value | Apache 2.0 | https://immutables.github.io/license.html|
org.immutables:builder | Apache 2.0 | https://immutables.github.io/license.html|
com.diffplug.osgi:com.diffplug.osgi.extension.sun.misc | no license necessary (polyfill module) ||
com.sun.activation:jakarta.activation | no license necessary (polyfill module) | |

**Comment by grthor** [comment]
- [ ] Due to the APL license of com.lowagie.itext we have to clearly state that we use their code.

**Comment by simlei** [comment]
We contacted the company from com.lowagie.itext and acquired permission to use their code. The TODO to mention the license properly is in another issue (#219).
