### ISSUE TITLE
Online help: introduce possibility to generate stylable table of contents

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#215]

**Comment by simlei** [comment]
https://github.com/jcryptool/crypto/commit/f521a6b1e9580f03a9d2e1c439ef296e676e54e2 shows exactly what is needed to generate a table of content for a help page.

This is the "raw", ungeneralized/abstracted form of applying the TOCbot library.
All involved `<script>...</script>` elements can well be centralized into a single `.js` file in `o.j.core.help` which is left open for now. This could boil down the changes needed to a page in above diff to

1) adding the `<div class="TOC">`, `<hr />`, and `<div class="content">` elements to mark what to TOCify and where to insert
2) add something like 

```
<script src="${JCTJS_HOST}/javascript/tocbot-4.11.2/dist/tocbot.min.js"></script>
<script>JCT_applyDefaultTOC("TOC", "content")</script>
```

Result currently looks like this:

![image](https://user-images.githubusercontent.com/982379/86915706-b94b7380-c122-11ea-9f8b-c61822f5195a.png)

**TODO**

1) [ ] generalize
2) [ ] apply everywhere it makes sense

**Comment by Leikani** [comment]
Hallo Herr Leischnig,

die neuen Hilfe mit dem Inhaltsverzeichnis oben sieht klasse aus!

Gruß, BE


Am 08.07.2020 um 14:01 schrieb Simon Leischnig:
> https://github.com/jcryptool/crypto/commit/f521a6b1e9580f03a9d2e1c439ef296e676e54e2 shows exactly what is needed to generate a table of content for a help page.
>
> This is the "raw", ungeneralized/abstracted form of applying the TOCbot library.
> All involved `<script>...</script>` elements can well be centralized into a single `.js` file in `o.j.core.help` which is left open for now. This could boil down the changes needed to a page in above diff to
>
> 1) adding the `<div class="TOC">`, `<hr />`, and `<div class="content">` elements to mark what to TOCify and where to insert
> 2) add something like 
>
> ```
> <script src="${JCTJS_HOST}/javascript/tocbot-4.11.2/dist/tocbot.min.js"></script>
> <script>JCT_applyDefaultTOC("TOC", "content")</script>
> ```
>
> Result currently looks like this:
>
> ![image](https://user-images.githubusercontent.com/982379/86915706-b94b7380-c122-11ea-9f8b-c61822f5195a.png)
>
> **TODO**
>
> 1) [ ] generalize
> 2) [ ] apply everywhere it makes sense
>

**Comment by simlei** [comment]
Considered done as soon as the JCTJS server works in builds, too; see #216

**Comment by simlei** [comment]
This has become somewhat easier in application to an html file with the new function `TOC_generate_default(...)` [1]

All that's needed to insert into a html file is two things:
- *javascript call:* https://github.com/jcryptool/core/blob/015ba9a10539205956d45e3d424f01581cff49c4/org.jcryptool.core.help/nl/en/help/users/toc.html#L7-L8
- *where the TOC is supposed to be*: (normally directly under `<h1>...</h1>`): https://github.com/jcryptool/core/blob/015ba9a10539205956d45e3d424f01581cff49c4/org.jcryptool.core.help/nl/en/help/users/toc.html#L14

[1] new function: `TOC_generate_default(heading-selector, [ content-selector="body" ])`
https://github.com/jcryptool/core/blob/5e927f0ea2fa69532551654d41bfc8d95d469f9d/org.jcryptool.core.help/javascript/bootstrap_jct_utilities.js#L43-L66
