### ISSUE TITLE
Keystore conflict with crypto providers

### ISSUE THREAD

**Issue by simlei** [jcryptool/core#224]
Keystore loading and item retrieval behavior is subject to the global static `java.security.Security` policy, which we set in https://github.com/jcryptool/core/blob/develop/de.flexiprovider/src/de/flexiprovider/FlexiProviderController.java

The keystore file from 2018 has beein reinstated (in a non-develop branch!) here: https://github.com/jcryptool/core/commit/0e5b7533b90e53ebc36bc9fb739d8e404b7d0b97

It looks like TLS is only working when sun providers have preference, while our keystore files only work when with flexiprovider Providers have preference. The branch `keystore_provider_experiment` has these changes: https://github.com/jcryptool/core/compare/keystore_provider_experiment

~However, at least as of 82e3b99, The change is only effective when the workspace is created fresh, i.e. when the shipped 2018 keystore is used. Then, it seems the format is saved to disk in the sun format.~ as of https://github.com/jcryptool/core/commit/280dcf81ea3e4f800055266c25ed22fd283e4ebb only an [unrelated error is thrown](https://github.com/jcryptool/core/issues/225):

**Comment by simlei** [comment]
merged branch keystore_provider_experiment as it seems to be what we're going for *but is untested*

**Comment by grthor** [comment]
Fix works in WB 11.07.20
Would suggest to close it.

**Comment by simlei** [comment]
Also have not seen this again since the fix introduced with https://github.com/jcryptool/core/commit/2ca1760287d845d94274412d73a09a01d8283c9a
