### ISSUE TITLE
Algorithm Perspective Introduction Overlay disappears on transition (Linux)

### ISSUE THREAD

**Issue by grthor** [jcryptool/core#227]
The algorithm prspective introduction plugin does not work correct on Linux.
Clicking on the arrows on the left and right side of the plugin does not trigger a slide to the next/previous image. 
On Windows this works, so its only a Linux issue.

![image](https://user-images.githubusercontent.com/20046726/92718181-c4f52980-f361-11ea-99bb-114281bed7e2.png)
The areas marked in red do not work.

**Comment by grthor** [comment]
Fixed with https://github.com/jcryptool/core/commit/de75991830c20980fbaac21122162edb6c5375a9

The overlay still disappears while the transition is in progress (duration ca. 1s). Afterwards it reappears.

Going to remove the "Bug" label and the milestone 1.0.0 target.

**Comment by simlei** [comment]
Confirm only during transition do the navigation controls disappear. (Ubuntu 20.04)

**Comment by simlei** [comment]
Should we close this issue? I think it's fine now.

**Comment by grthor** [comment]
I think we can close it. 
Thi issue is acceptable
