### ISSUE TITLE
Wiki cleanup

### ISSUE THREAD

**Issue by grthor** [jcryptool/core#245]
I just did a little search on Wiki. The search took quite a long time because there are 39 pages. However, many of the pages contain duplicate information. Therefore, I would delete 12 pages. This would increase the search speed.
Below is a list of which pages I would delete and why:
- https://github.com/jcryptool/core/wiki/Getting-started-with-programming-for-JCrypTool----with-Oomph because it contains the same information as https://github.com/jcryptool/core/wiki/Getting-started-as-a-JCrypTool-Developer.
- https://github.com/jcryptool/core/wiki/Resources. The article says: "We use the following technologies. If you have questions regarding these, look at the following articles." Google does this job much better than this page.
- All seven Release articles (e.g. https://github.com/jcryptool/core/wiki/releases-RC8). The same informations are listet in https://github.com/jcryptool/core/wiki/Release-Plan
- https://github.com/jcryptool/core/wiki/Release-Information contains just a list of links to the release articles. The release articles are linked in from the menu on the right too.
- https://github.com/jcryptool/core/wiki/Google-Summer-of-Code-2015 and https://github.com/jcryptool/core/wiki/Google-Summer-of-Code-2016 contain the same list of future projects as in https://github.com/jcryptool/core/wiki/Project-Ideas

What do you think about deleting the articles? No information would be lost.

**Comment by simlei** [comment]
All fine with me :)
I'll update the release plan page the next days...

**Comment by grthor** [comment]
You don't have to worry about it. I can do that too.

**Comment by grthor** [comment]
The cleanup ist finished. 

The single files for releases are merged into the release plan. https://github.com/jcryptool/core/wiki/Release-Plan

The number of pages in wiki was removed from 39 to 27.
