### ISSUE TITLE
MacOS X download contains version 1.0.5 instead of 1.0.6

### ISSUE THREAD

**Issue by suschizu** [jcryptool/core#250]
Noticed that the latest Mac OS download contains the wrong version number 

<img width="242" alt="Screen Shot 2021-06-30 at 22 48 07" src="https://user-images.githubusercontent.com/16004333/124029637-a433b880-d9f5-11eb-91f3-7779d52eaba9.png">

**Comment by simlei** [comment]
Good catch, thanks! Binaries with according changes have been published now, replacing the old ones.
