### ISSUE TITLE
Password

### ISSUE THREAD

**Issue by Timothy-Rufus** [jcryptool/core#260]
Whenever I run the given code on my mac it asks for password, but doesn't allow me to type anything in that field

**Comment by simlei** [comment]
Hi, 

could you provide a screenshot of where that password is asked?

Thanks!

**Comment by heylaila** [comment]
Hello I am a mac user and followed all the steps outlined and also am being asked for a password

**Comment by heylaila** [comment]
<img width="575" alt="Screenshot 2023-03-30 at 6 23 38 PM" src="https://user-images.githubusercontent.com/129458283/228977216-c4bafa32-7c20-46bf-9d0d-2efbc8b72087.png">

**Comment by tassadarius** [comment]
@be4 Did any problems occur on Mac regarding passwords?

If not, I would suggest to close this ticket as it seems to be stale.
