### ISSUE TITLE
JRE required on Mac OS (13.5) - jcryptool v1.0.9

### ISSUE THREAD

**Issue by jarv-git** [jcryptool/core#263]
Hi,

Although jcryptool v1.0.9 release notes indicate:

_- A standalone JRE is now delivered built-into the JCT product for Mac OS; JCT runs now standalone on all operating systems_

I got the following message when trying to run it: 

**A Java Runtime Environment (JRE) or Java Development Kit (JDK) must be available in order to run JCrypTool.**

_No Java virtual machine was found after searching the following locations:
../Eclipse/features/org.jcryptool.thirdparty.jre.macosx.feature_1.0.9/jre/Contents/Home/lib/jli/libjli.dylib_

I'm using M1 laptop.

Any idea why I am getting this message?

Thanks!

**Comment by simlei** [comment]
Hi,

Thanks for reporting this. We unfortunately had problems with this version's Mac JVM. We're going to have this resolved soon. I'll give an update here.

**Comment by simlei** [comment]
Hi @jarv-git ,
I believe the MacOS problems you've described have been fixed in today's re-release of v1.0.9! Check it out and tell us if it works for you: https://github.com/jcryptool/core/releases/tag/1.0.9

**Comment by jarv-git** [comment]
Now is working.

Thanks!
