### ISSUE TITLE
Automatic update site check once a month

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#28]
Configure the JCrypTool update manager to check for updates once a month. Automatic update check is already active, but this check is done every startup which is too often.

**Comment by simlei** [comment]
Do we want to do an updated Feature request with eclipse update page features? I myself don't know too much about the update site mechanism right now.

**Comment by simlei** [comment]
We release at least weekly now; this issue seems obsolete.

**Comment by grthor** [comment]
Just for the record: The update check at each start has remained. But since we only upload new data to the UpdateSite every few months, the user will only get a notification about available updates every few months. In my eyes this is a good rhythm at the moment.
