### ISSUE TITLE
Incomplete FlexiProvider 1.7.0p3 integration

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#4]
The algorithms.xml file for the latest FlexiProvider version has not been updated and contains an older version. A new algorithms.xml must be generated and integrated in JCrypTool. This is a minor bug since the latest version is used, however some wizard may reflect an older version.

**Comment by simlei** [comment]
I am working on something to make updating the algorithms.xml with new BC releases obsolete. In the meantime, this seems to be outdated and could be newly raised with fresh info if necessary.
