### ISSUE TITLE
Extend the FlexiProvider New-Key-Wizard

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#5]
The (new) key wizard in the FlexiProvider view should be extended. Currently only the key length can be configured, but this is not suitable for all types of keys.

For GMSS-keys there are actually three different parameters a user could change:
defh: An array with the depths of the different trees in the GMSS-key
defw: Parameter how many bits should be processed at once
defk: Parameter for the AuthPath.
See: http://www.flexiprovider.de/javadoc/flexiprovider/docs/index.html for further details.

Other examples are the keys for McEliece, Niederreiter or CMSS.

The key-configuration part should be created as flexible as it is done for the algorithms in the FlexiProvider perspective.

**Comment by simlei** [comment]
I am currently working on a complete integration of the BouncyCastle crypto provider. FlexiProvider is already merged into Bouncycastle and the issues with too little configuration options will be fully addressed in the future. to be raised again with fresh informations if necessary.
