### ISSUE TITLE
Algorithm perspective: Decrypt operation asks for private key password immediately

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#59]
Add an algorithm like RSA to the operations view and drag&drop a matching private key onto the key entry. The password dialog opens immediately and asks for the password. The user has to enter the password and click the start button to decrypt the content. The correct way is to let the user drag&drop the key without any password dialog, let him click on execute and then show the password dialog.

**Comment by simlei** [comment]
I am currently working on a complete integration of the BouncyCastle crypto provider. FlexiProvider is already merged into Bouncycastle and not longer maintained. The BouncyCastle integration will feature full customizability and functional-style lazy evaluation of AST-like data structures which seem to be a good candidate to make such API problems as of this issue unlikely. Thus, I think it's appropriate to tag this as "won't fix". To be raised again with fresh informations if necessary.
