### ISSUE TITLE
FlexiProvider: Provide help pages

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#7]
Provide extensive English and German help for the FlexiProvider perspective and all its views/ wizards/ actions. Link the pages from the matching context help pages.

**Comment by simlei** [comment]
As with any Flexiprovider-related issues, this is outdated as Flexiprovider is no longer maintained by TU Darmstadt and was merged into Bouncycastle. Bounczcastle/integration into JCrypTool with rich customizability is coming soon! to be raised again zwith fresh informations if necessary.
