### ISSUE TITLE
Hide keystore entries starting with "JCT"

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#71]
Hide all keystore entries starting with capital "JCT" in the keystore view as well as in all drop down boxes listing those keys. Only direct KeyStoreManager requests e.g. for a private key starting with "JCT" should expose these internal keys. 

Add a menu entry in the Keystore view to show/ hide internal keys. Default should be to hide them. Explain this feature in the user help and the context help for the view.

Update the developer documentation with information about these internal keys.

**Comment by simlei** [comment]
Are there still such "internal keys?" Can't find any right now...

**Comment by grthor** [comment]
I took a look into the keystore with the java keytool and there are no aliases that start with JCT. This issue is a remnant from another time and was never closed. Therefore I will close the issue now.
