### ISSUE TITLE
Add Eclipse Commands support to Crypto Explorer and JCrypTool menu

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#79]
Crypto Explorer view (plug-in org.jcryptool.core.views) and the main JCrypTool menu (provided by org.jcryptool.core) must support Eclipse Commands in addition to deprecated Eclipse Actions. Both Commands and Actions should co-exist if possible. First step would be to provide an extension point for algorithm crypto plug-ins which requires Commands instead of Actions for Crypto plug-ins. 

A crypto plug-in should prove usability. Either create a new crypto plug-in or use one in the crypto plug-ins located in our crypto repository.

Develop in Core master branch, do not break any existing crypto plug-in.

Algorithm extension point is org.jcryptool.core.operations.algorithms in the org.jcrytpool.core.operations plug-in. This extension point should be used in the future, but it should be possible to either provide a Command class or an Action class as implementation. Use the deprecated flag on Action to push towards Commands.

**Comment by grthor** [comment]
I think this all actions are replaced by commands.

All algorithms are integrated via the extension point org.jcryptool.core.operations.algorithms 

But I don't know if I missed an action. We can talk about it on Tuesday. Because when it is done we could close the issue.

**Comment by simlei** [comment]
With both the quick access bar supporting the Crypto Explorer view and menu items, this is not essential anymore I think. Restructuring of Actions/Commands only seem viable in the context of e.g. e4-migration, so I'll tag it thusly.
