### ISSUE TITLE
Eclipse Commands support for non-algorithm extension points

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#81]
Follow up task on https://github.com/jcryptool/core/issues/79

Non-algorithm extension points for Analysis, Visualizations and Games must support Eclipse Commands as Algorithms does.

**Comment by hfriedr** [comment]
The extension points for Analyses, Visualizations, and Games are much simpler and do not involve a class from either the Action or Command framework as the Algorithm extension point does.  What makes you think there is anything that needs to be done here?  I could be wrong, but I do not see any potential for something to be done in this respect.

**Comment by dschadow** [comment]
Closed, no change required for Command support.
