### ISSUE TITLE
e4: Replace org.eclipse.ui.actionSets

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#82]
org.eclipse.ui.actionSets (actionSet and action elements in plugin.xml) is deprecated with Eclipse 4. Replace all occurrences with commands.

**Comment by hfriedr** [comment]
Currently there is a single actionSet left (in org.jcryptool.core), the others have already been replaced.

**Comment by hfriedr** [comment]
While I temporarily "imported" an old actionSet from the org.jcryptool.core.action plug-in that had been removed, I changed the Open File implementation from an Action to a Command, and so the actionSet is gone again.

**Comment by simlei** [comment]
I am currently only seeing one usage of actionSets left in JCT: in org.jcryptool.core, the EditorsPulldownAction is still registered this way.

```
<extension
         point="org.eclipse.ui.actionSets">
      <actionSet
            id="org.jcryptool.core.editorsActionSet"
            label="%editors.actionSet.label"
            visible="true">
         <action
               class="org.jcryptool.core.actions.ShowEditorsPulldownMenuAction"
               icon="icons/editors.gif"
               id="EditorsToolbar.EditorsPulldownAction"
               label="%editors.action.label"
               style="pulldown"
               toolbarPath="org.jcryptool.core.toolbar/fileStart"
               tooltip="%editors.action.tooltip">
         </action>
      </actionSet>
   </extension>
```

**Comment by grthor** [comment]
I looked at the action. In my opinion, it has already been replaced by a command.

There is the ShowEditorsPulldownMenuAction and the ShowEditorsPulldownMenu in the package org.jcryptool.core.commands which makes me feel like the action has already been replaced. The ShowEditorsPulldownMenu implements AbstractHandler. It is already registered as a command in the plugin.xml but is not used.

I would delete the code and close the issue.

Maybe @simlei can take a look.

**Comment by grthor** [comment]
Small update.
The action adds a drop down menu to the toolbar. Screenshot.
<img width="389" alt="showeditorspulldownmenuaction" src="https://user-images.githubusercontent.com/20046726/46580849-06218800-ca2d-11e8-9c36-2f40a009e5fe.png">
The drop-down menu displays all registered editors.
The difficulty is to add a variable number of commands to the drop-down menu.
It has already been tried to replace the actions with commands. All except for thisaction have been replaced.
