### ISSUE TITLE
Context help not visible after Eclipse 4.4 migration

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#87]
Context help view (visible on the left bottom) is not visible in bottom left corner at first. Visible after opening a crypto view.

**Comment by hfriedr** [comment]
Created Eclipse Bug 459150 - ModelServiceImpl.hideLocalPlaceholders() disposes of objects still needed, reporting that I commented out line #922 in ModelServiceImpl.java:

// local.setToBeRendered(false);

to alleviate the symptom.

**Comment by hfriedr** [comment]
Added a comment to Eclipse bug #444472 outlining a fix along the lines of the bug fix for bug #407084.

**Comment by simlei** [comment]
This is the referenced bugtracker thread:
https://bugs.eclipse.org/bugs/show_bug.cgi?id=444472

Seems to be nothing moving there.
Reopen if necessary please, but I think with https://github.com/jcryptool/core/issues/87#issuecomment-72880028 we can close this.
