### ISSUE TITLE
F1 not working

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#91]
Pressing F1 has no effect, dynamic help view does not show. Clicking on the help icon in a view is working.

**Comment by hfriedr** [comment]
F1 works for me (Luna SR1a, Windows 7), at least for the Number Shark game and the Crypto Explorer view.

**Comment by dschadow** [comment]
Assigned back to me, must be an OS X problem.

**Comment by dschadow** [comment]
Can't reproduce that any more.
