### ISSUE TITLE
Open file icon and menu entry missing

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#97]
The file menu and the main toolbar do not show the 'Open file' entry/ icon any more. The selected file must be opened in the associated editor (hex/text).

**Comment by hfriedr** [comment]
The German text "Datei öffnen..." on the menu item seems to come from the org.jcryptool.core.actions plug-in, which is still there in 0.9.8 but was removed recently.

**Comment by dschadow** [comment]
OK, then please restore the required code and move it into the org.jcryptool.core plug-in. In case this requires a new dependency from org.jcryptool.core to one of the editor plug-ins consider moving the open file code into org.jcryptool.editor.text or try to get rid of the dependency.

**Comment by hfriedr** [comment]
OK, moved the code to org.jcryptool.core and changed it from an IWorkbenchWindowActionDelegate to an AbstractHandler.  There was no dependency to one of the editor plug-ins.

**Comment by hfriedr** [comment]
Instead of opening a file, OpenFileHandler would throw a NullPointerException due to the use of an uninitialized variable called window.  Now using PlatformUI and its methods instead.  Therefore, the restored Open File menu item and icon will actually open a file now.
