### ISSUE TITLE
File Drag&Drop in editor area not working

### ISSUE THREAD

**Issue by dschadow** [jcryptool/core#98]
Drag&Drop of a file from the file system (Finder, Windows Explorer) in the editor area (all editors closed) is not working. It should be possible to open a file this way, no matter whether there is an editor opened (and the file is dropped onto an open editor page) or all editors are closed. Onto an opened editor is optional, but editor area drop is required.

**Comment by hfriedr** [comment]
I did manage to enable dropping a file (from JCrypTool's File Explorer at least) on an open text editor, but dropping a file on the Editor Area somehow does not work yet.  It should be fairly straightforward but somehow the configured DropTargetListener shows no reaction.  I did not push this intermediate solution so far as I am not sure it makes much sense.

**Comment by hfriedr** [comment]
By the way, the (questionable) drop onto an open text editor works from Windows Explorer, too.

**Comment by hfriedr** [comment]
Update:  the DropTargetListener configured for the Editor Area does show a reaction if the file is dragged from Windows Explorer, just not if the file is dragged from the JCrypTool File Explorer, which is what I had been trying all the time.  So it should be possible to make it work for this case (dragging from Windows Explorer) at least.

**Comment by hfriedr** [comment]
So the Editor Area now accepts drops from Windows Explorer onto both an empty Editor Area and an open hex editor, and drops from both Windows Explorer and the JCrypTool File Explorer onto an open text editor.
Implementing drag & drop for the hex editor in the same way I did for the text editor would most likely require changing the net.sourceforge.ehep plug-in, which does not "belong" to the JCrypTool team and therefore should most probably be left alone.  Anyway, the requirement was to support drag & drop from Windows Explorer, which is now supported by an empty Editor Area as well as by open editors.

**Comment by dschadow** [comment]
nice job!
